config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :developers
  # resources :data_access_requests
  resources :api_logs
  resources :api_keys
  resources :check_ins
  resources :loyalty_programs
  resources :offers
  resources :inventories
  resources :orders
  resources :menu_items
  resources :reservations
  resources :tables
  resources :reviews
  resources :staff_schedules
  resources :bookings
  resources :guests
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
 root 'dashboard#index'
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :developer
end

app/models/api_log.rb
class ApiLog < ApplicationRecord
  belongs_to :api_key
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :guest
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :guest
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :api_keys
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :guest
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :reservation
  belongs_to :menu_item
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :guest
  belongs_to :table
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :guest
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff_schedule.rb
class StaffSchedule < ApplicationRecord
  belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/staff_schedules_controller.rb
class StaffSchedulesController < ApplicationController
  before_action :set_staff_schedule, only: %i[ show edit update destroy ]

  # GET /staff_schedules or /staff_schedules.json
  def index
    @staff_schedules = StaffSchedule.all
  end

  # GET /staff_schedules/1 or /staff_schedules/1.json
  def show
  end

  # GET /staff_schedules/new
  def new
    @staff_schedule = StaffSchedule.new
  end

  # GET /staff_schedules/1/edit
  def edit
  end

  # POST /staff_schedules or /staff_schedules.json
  def create
    @staff_schedule = StaffSchedule.new(staff_schedule_params)

    respond_to do |format|
      if @staff_schedule.save
        format.html { redirect_to staff_schedule_url(@staff_schedule), notice: "Staff schedule was successfully created." }
        format.json { render :show, status: :created, location: @staff_schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_schedules/1 or /staff_schedules/1.json
  def update
    respond_to do |format|
      if @staff_schedule.update(staff_schedule_params)
        format.html { redirect_to staff_schedule_url(@staff_schedule), notice: "Staff schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @staff_schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_schedules/1 or /staff_schedules/1.json
  def destroy
    @staff_schedule.destroy!

    respond_to do |format|
      format.html { redirect_to staff_schedules_url, notice: "Staff schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_schedule
      @staff_schedule = StaffSchedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_schedule_params
      params.require(:staff_schedule).permit(:user_id, :shift_start, :shift_end, :role)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/staff_schedules_helper.rb
module StaffSchedulesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/staff_schedules/_form.html.erb
<%= form_with(model: staff_schedule, class: "contents") do |form| %>
  <% if staff_schedule.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(staff_schedule.errors.count, "error") %> prohibited this staff_schedule from being saved:</h2>

      <ul>
        <% staff_schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :shift_start %>
    <%= form.datetime_field :shift_start, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :shift_end %>
    <%= form.datetime_field :shift_end, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :role %>
    <%= form.text_field :role, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/staff_schedules/_staff_schedule.html.erb
<div id="<%= dom_id staff_schedule %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= staff_schedule.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shift start:</strong>
    <%= staff_schedule.shift_start %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shift end:</strong>
    <%= staff_schedule.shift_end %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Role:</strong>
    <%= staff_schedule.role %>
  </p>

</div>

app/views/staff_schedules/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing staff schedule</h1>

  <%= render "form", staff_schedule: @staff_schedule %>

  <%= link_to "Show this staff schedule", @staff_schedule, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to staff schedules", staff_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/staff_schedules/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Staff schedules" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Staff schedules</h1>
    <%= link_to "New staff schedule", new_staff_schedule_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="staff_schedules" class="min-w-full">
    <% @staff_schedules.each do |staff_schedule| %>
      <%= render staff_schedule %>
      <p>
        <%= link_to "Show this staff schedule", staff_schedule, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/staff_schedules/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New staff schedule</h1>

  <%= render "form", staff_schedule: @staff_schedule %>

  <%= link_to "Back to staff schedules", staff_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/staff_schedules/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @staff_schedule %>

    <%= link_to "Edit this staff schedule", edit_staff_schedule_path(@staff_schedule), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to staff schedules", staff_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this staff schedule", @staff_schedule, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>