config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  resources :developers
  # resources :data_access_requests
  resources :api_logs
  resources :api_keys
  resources :check_ins
  resources :loyalty_programs
  resources :offers
  resources :inventories
  resources :orders
  resources :menu_items
  resources :reservations
  resources :tables
  resources :reviews
  resources :staff_schedules
  resources :bookings
  resources :guests
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
 root 'dashboard#index'
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :developer
end

app/models/api_log.rb
class ApiLog < ApplicationRecord
  belongs_to :api_key
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :guest
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :guest
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :api_keys
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :guest
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :reservation
  belongs_to :menu_item
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :guest
  belongs_to :table
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :guest
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/staff_schedule.rb
class StaffSchedule < ApplicationRecord
  belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :set_api_key, only: %i[ show edit update destroy ]

  # GET /api_keys or /api_keys.json
  def index
    @api_keys = ApiKey.all
  end

  # GET /api_keys/1 or /api_keys/1.json
  def show
  end

  # GET /api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys or /api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to api_key_url(@api_key), notice: "Api key was successfully created." }
        format.json { render :show, status: :created, location: @api_key }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_keys/1 or /api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to api_key_url(@api_key), notice: "Api key was successfully updated." }
        format.json { render :show, status: :ok, location: @api_key }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1 or /api_keys/1.json
  def destroy
    @api_key.destroy!

    respond_to do |format|
      format.html { redirect_to api_keys_url, notice: "Api key was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_key
      @api_key = ApiKey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_key_params
      params.require(:api_key).permit(:developer_id, :api_key, :status)
    end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/api_keys/_api_key.html.erb
<div id="<%= dom_id api_key %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Developer:</strong>
    <%= api_key.developer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Api key:</strong>
    <%= api_key.api_key %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= api_key.status %>
  </p>

</div>

app/views/api_keys/_form.html.erb
<%= form_with(model: api_key, class: "contents") do |form| %>
  <% if api_key.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(api_key.errors.count, "error") %> prohibited this api_key from being saved:</h2>

      <ul>
        <% api_key.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :developer_id %>
    <%= form.text_field :developer_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :api_key %>
    <%= form.text_field :api_key, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing api key</h1>

  <%= render "form", api_key: @api_key %>

  <%= link_to "Show this api key", @api_key, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to api keys", api_keys_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/api_keys/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Api keys" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Api keys</h1>
    <%= link_to "New api key", new_api_key_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="api_keys" class="min-w-full">
    <% @api_keys.each do |api_key| %>
      <%= render api_key %>
      <p>
        <%= link_to "Show this api key", api_key, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/api_keys/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New api key</h1>

  <%= render "form", api_key: @api_key %>

  <%= link_to "Back to api keys", api_keys_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/api_keys/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @api_key %>

    <%= link_to "Edit this api key", edit_api_key_path(@api_key), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to api keys", api_keys_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this api key", @api_key, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>